instance_name      = "Pritunl_VPN_prod"
tag_environment    = "production"
tag_ambiente       = "terraform-prod"
vpc_name           = "production"
vpc_cidr_block        = "172.80.0.0/16"
public_subnet_cidrs   = ["172.80.1.0/24", "172.80.2.0/24"]
private_subnet_cidrs  = ["172.80.3.0/24", "172.80.4.0/24"]
availability_zones    = ["us-east-1a", "us-east-1b"]
ecr_name           = "api-production"
ecr_service_name   = "api-production"
ecs_cpu            = "2048"
ecs_memory         = "4096"
domain_name        = "prod.brian.pt"
rds_instance_type  = "db.t4g.small"
cloudtrail_name           = "cloudtrail-monitor-prod"
cloudtrail_s3_bucket_prefix = "cloudtrail-auditoria-prod"
cloudtrail_s3_key_prefix  = "prod"
iam_role_name          = "role-acesso-ssm2-prod"
instance_profile_name  = "instance-profile-acesso-ssm2-prod"
ami_id            = "ami-096ea6a12ea24a797"
instance_type     = "t4g.micro"
ecs_cluster_name = "production"
ecs_service_name = "api-production"
ecs_desired_count = 2
container_name   = "api-production"
container_port   = 3000
alb_name             = "production"
alb_target_group_name = "ecs-api"
rds_engine = "postgres"
rds_engine_version = "16.3"
rds_parameter_group    = "default.postgres16"
rds_db_name            = "api"
rds_identifier = "api-production"
rds_multi-az = true
rds_delete_automated_backups = false
rds_username = "postgres"
rds_backup_retention_period = 7
waf_acl_name     = "waf-production"
waf_description  = "Web ACL para ambiente de produção"
waf_metric_name  = "waf-prod-metric"
