instance_name      = "Pritunl_VPN_dev"
tag_environment    = "development"
tag_ambiente       = "terraform-dev"
vpc_name           = "development"
vpc_cidr_block        = "172.90.0.0/16"
public_subnet_cidrs   = ["172.90.1.0/24", "172.90.2.0/24"]
private_subnet_cidrs  = ["172.90.3.0/24", "172.90.4.0/24"]
availability_zones    = ["us-east-1a", "us-east-1b"]
ecr_name           = "api-development"
ecr_service_name   = "api-development"
ecs_cpu            = "512"
ecs_memory         = "1024"
domain_name        = "brian.pt"
rds_instance_type  = "db.t4g.micro"
cloudtrail_name           = "cloudtrail-monitor-dev"
cloudtrail_s3_bucket_prefix = "cloudtrail-auditoria-dev"
cloudtrail_s3_key_prefix  = "dev"
iam_role_name          = "role-acesso-ssm2-dev"
instance_profile_name  = "instance-profile-acesso-ssm2-dev"
ami_id            = "ami-096ea6a12ea24a797"
instance_type     = "t4g.micro"
ecs_cluster_name = "development"
ecs_service_name = "api-development"
ecs_desired_count = 1
container_name   = "api-development"
container_port   = 3000
alb_name             = "development"
alb_target_group_name = "ecs-api-dev"
rds_engine = "postgres"
rds_engine_version = "16.3"
rds_parameter_group    = "default.postgres16"
rds_db_name            = "api_dev"
rds_identifier = "api-development"
rds_multi-az = false
rds_delete_automated_backups = true
rds_username = "postgres"
rds_backup_retention_period = 0
waf_acl_name     = "waf-development"
waf_description  = "Web ACL para ambiente de desenvolvimento"
waf_metric_name  = "waf-dev-metric"
ecs_max_capacity = 0
ecs_min_capacity = 0
scale_up_cpu_threshold = 75
scale_down_cpu_threshold = 25
scale_up_cooldown = 300
scale_down_cooldown = 300