name: Build & Deploy - Production

on:
  repository_dispatch:
    types: [deploy-production]
  push:
    branches:
      - main  

jobs:
  workflow:
    uses: brianmonteiro54/devops-template/.github/workflows/bundle.yml@main


    with:
      IMAGE_NAME: api-production
      TASK_NAME: api-production
      CONTAINER_NAME: api-production
      ECS_SERVICE: api-production
      ECS_CLUSTER: production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      US_EAST_1_BUNDLE: ${{ secrets.PRIVATE_KEY }}

