name: Build & Deploy - development

on:
  repository_dispatch:
    types: [deploy-development]
  push:
    branches:
      - develop 

jobs:
  workflow:
    uses: brianmonteiro54/devops-template/.github/workflows/bundle.yml@v1.4


    with:
      IMAGE_NAME: api-development
      TASK_NAME: api-development
      CONTAINER_NAME: api-development
      ECS_SERVICE: api-development
      ECS_CLUSTER: development
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}