name: Build & Deploy - Production

on:
  repository_dispatch:
    types: [deploy-production]
  push:
    branches:
      - main  

jobs:
  workflow:
    uses: brianmonteiro54/devops-template/.github/workflows/bundle.yml@v1.4


    with:
      IMAGE_NAME: api-production
      TASK_NAME: api-production
      CONTAINER_NAME: api-production
      ECS_SERVICE: api-production
      ECS_CLUSTER: production
    secrets:
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}